




DB_HOST: localhost
DB_NAME: nyayawelfare
DB_USERNAME: postgres
DB_PASSWORD: admin@123
DB_PORT : 5432
DATABASE: postgresql
DIALECT : org.hibernate.dialect.PostgreSQLDialect

SECRET_KEY: +3bGl4GqFhQLFqxcF+izG7ABBPrPOFDcZPrrV2se3ciF/jSYk72ZVmlU5PxO6iv6ohVT6w3WSQ7YoicvF3gbmdazy3TCPakUbdC22PJWvVo=

sendinblue_api: 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
sendinblue_mail: https://api.sendinblue.com/v3/smtp/email

app_name: Loan Hero Application
app_email: info@loanhero.com

cloud_name: dxaaqbimm
cloud_secret: EBk8vZo8lTn57pGa89bvAAx8R9E
cloud_key: 877683365182835

# 3 hours
access_token: 10800
# 1 week
refresh_token: 604800

